In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.shape

(3, 3)

In [7]:
a*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
a+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])